CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS buildings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    city TEXT NOT NULL,
    district TEXT,
    name TEXT NOT NULL,
    address TEXT,
    object_type TEXT,
    document_type TEXT,
    category TEXT,
    fire_resistance_degree TEXT,
    floors_count INTEGER,
    total_area DOUBLE PRECISION,
    construction_type TEXT,
    nearest_fire_department TEXT,
    distance_to_fire_department DOUBLE PRECISION,
    arrival_time_minutes DOUBLE PRECISION,
    route_description TEXT,
    fire_rank TEXT,
    owner_name TEXT,
    owner_phone TEXT,
    technical_manager_name TEXT,
    technical_manager_phone TEXT,
    security_phone TEXT,
    dispatcher_phone TEXT,
    private_fire_service_phone TEXT,
    power_supply_info TEXT,
    heating_info TEXT,
    water_supply_info TEXT,
    ventilation_info TEXT,
    smoke_removal_info TEXT,
    fire_alarm_info TEXT,
    fire_extinguishing_systems JSONB,
    evacuation_routes_count INTEGER,
    potential_hazards TEXT,
    complexity_features TEXT,
    auxiliary_means TEXT,
    estimated_forces JSONB,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    source TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (city, name)
);
